// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "bus_services",
    checkConstraints: {
      bus_services_xata_id_length_xata_id: {
        name: "bus_services_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {},
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_bus_services_xata_id_key: {
        name: "_pgroll_new_bus_services_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "description",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "service_name",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "service_number",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
  {
    name: "route_stops",
    checkConstraints: {
      route_stops_xata_id_length_xata_id: {
        name: "route_stops_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {
      route_id_link: {
        name: "route_id_link",
        columns: ["route_id"],
        referencedTable: "routes",
        referencedColumns: ["xata_id"],
        onDelete: "SET NULL",
      },
      stop_id_link: {
        name: "stop_id_link",
        columns: ["stop_id"],
        referencedTable: "stops",
        referencedColumns: ["xata_id"],
        onDelete: "SET NULL",
      },
    },
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_route_stops_xata_id_key: {
        name: "_pgroll_new_route_stops_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "route_id",
        type: "link",
        link: { table: "routes" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"routes"}',
      },
      {
        name: "route_stop_id",
        type: "int",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "sequence_number",
        type: "int",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "stop_id",
        type: "link",
        link: { table: "stops" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"stops"}',
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
  {
    name: "routes",
    checkConstraints: {
      routes_xata_id_length_xata_id: {
        name: "routes_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {
      service_id_link: {
        name: "service_id_link",
        columns: ["service_id"],
        referencedTable: "bus_services",
        referencedColumns: ["xata_id"],
        onDelete: "SET NULL",
      },
    },
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_routes_xata_id_key: {
        name: "_pgroll_new_routes_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "route_name",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "service_id",
        type: "link",
        link: { table: "bus_services" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"bus_services"}',
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
  {
    name: "stop_times",
    checkConstraints: {
      stop_times_xata_id_length_xata_id: {
        name: "stop_times_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {
      route_stop_id_link: {
        name: "route_stop_id_link",
        columns: ["route_stop_id"],
        referencedTable: "route_stops",
        referencedColumns: ["xata_id"],
        onDelete: "SET NULL",
      },
      trip_id_link: {
        name: "trip_id_link",
        columns: ["trip_id"],
        referencedTable: "trips",
        referencedColumns: ["xata_id"],
        onDelete: "SET NULL",
      },
    },
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_stop_times_xata_id_key: {
        name: "_pgroll_new_stop_times_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "departure_time",
        type: "int",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "is_skipped",
        type: "bool",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "route_stop_id",
        type: "link",
        link: { table: "route_stops" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"route_stops"}',
      },
      {
        name: "trip_id",
        type: "link",
        link: { table: "trips" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"trips"}',
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
  {
    name: "stops",
    checkConstraints: {
      stops_xata_id_length_xata_id: {
        name: "stops_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {},
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_stops_xata_id_key: {
        name: "_pgroll_new_stops_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "description",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "stop_name",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
  {
    name: "trips",
    checkConstraints: {
      trips_xata_id_length_xata_id: {
        name: "trips_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {
      route_id_link: {
        name: "route_id_link",
        columns: ["route_id"],
        referencedTable: "routes",
        referencedColumns: ["xata_id"],
        onDelete: "SET NULL",
      },
      service_id_link: {
        name: "service_id_link",
        columns: ["service_id"],
        referencedTable: "bus_services",
        referencedColumns: ["xata_id"],
        onDelete: "SET NULL",
      },
    },
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_trips_xata_id_key: {
        name: "_pgroll_new_trips_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "day_of_week",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "route_id",
        type: "link",
        link: { table: "routes" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"routes"}',
      },
      {
        name: "service_id",
        type: "link",
        link: { table: "bus_services" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"bus_services"}',
      },
      {
        name: "start_time",
        type: "int",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "trip_id",
        type: "int",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL: "https://ManApp-35a8tu.us-east-1.xata.sh/db/ManApp",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
